import Project from "../type/Project";

const Projects = [
    // {
    //     _id: 1,
    //     Title: "Project 1",
    //     Description: "This is a project 1 description",
    //     Status: "Completed",
    //     Technologies: ["React", "Node", "MongoDB"],
    //     StartDate: "2020-01-01",
    //     EndDate: "2020-01-31",
    // },
    // {
    //     _id: 2,
    //     Title: "Project 2",
    //     Description: "This is a project 2 description",
    //     Status: "Completed",
    //     Technologies: ["Java", "JavaFx", "MySQL"],
    //     StartDate: "2020-02-01",
    //     EndDate: "2020-02-28",
    // },
    // {
    //     id: 3,
    //     Title: "Project 3",
    //     Description: "This is a project 3 description",
    //     Status: "Completed",
    //     Technologies: ["Angular", "Node", "MongoDB"],
    //     StartDate: "2021-03-01",
    //     EndDate: "2022-01-31",
    // },
    // {
    //     id: 4,
    //     Title: "Project 4",
    //     Description: "This is a project 4 description",
    //     Status: "Completed",
    //     Technologies: ["Angular", "Firebase"],
    //     StartDate: "2022-03-01",
    //     EndDate: "2023-01-15",
    // },
    // {
    //     id: 5,
    //     Title: "Project 5",
    //     Description: "This is a project 5 description",
    //     Status: "Completed",
    //     Technologies: ["Java", "JavaFx", "MySQL"],
    //     StartDate: "2022-03-01",
    //     EndDate: "2023-01-15",
    // },
    // {
    //     id: 6,
    //     Title: "Chess",
    //     Description: "Chess game with AI",
    //     Status: "In Progress",
    //     Technologies: ["Python", "Pygame", "AI"],
    //     StartDate: "2020-03-01",
    //     EndDate: "TBD",
    // },
    // {
    //     id: 7,
    //     Title: "Project 7",
    //     Description: "This is a project 7 description",
    //     Status: "Completed",
    //     Technologies: ["React", "Firebase"],
    //     StartDate: "2022-03-01",
    //     EndDate: "2023-01-15",
    // },
    // {
    //     id: 8,
    //     Title: "Project 8",
    //     Description: "This is a project 8 description",
    //     Status: "Completed",
    //     Technologies: ["Svelte", ".NET"],
    //     StartDate: "2022-05-01",
    //     EndDate: "2023-07-15",
    // },
    // {
    //     id: 9,
    //     Title: "Project 9",
    //     Description: "This is a project 9 description",
    //     Status: "Completed",
    //     Technologies: ["Angular", "Firebase"],
    //     StartDate: "2022-03-01",
    //     EndDate: "2023-01-15",
    // }

]
